### ISSUE TITLE
Consider `set -o errexit` in scripts

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eosio-project-demux-example#13]
Nice modular shell scripts!

Consider adding `set -o errexit` at the top in most scripts.  This gives you control over the entire process so for example you can ensure that `./quick_start.sh` stops immediately because it called a script that also stopped immediately on the first error return code.  The critical error is the last thing shown.  I use it in all my scripts..  You may find you need to add an occasional pre-condition (test for a file or directory existence) and use that to avoid a error return code from your command.  There is also a way to hide an error return code if you need that (that is rare).

**Comment by TaraTritt** [comment]
Thanks, @jcalfee! This sounds like a great idea. I will add this to the scripts and open a PR after testing.

**Comment by TaraTritt** [comment]
#14
