### ISSUE TITLE
Suffix "/opt/eosio/bin" to the path

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eosio-project-demux-example#18]
If you suffix the PATH with "/opt/eosio/bin", your eosio commands would be more environment friendly.  

Use:
```bash
eosiocpp ..
```

Intead of:
```bash
./eosiocpp ..
```

The PATH suffix will be reset after the script is done then re-added the next invocation:
```bash
PATH="$PATH:/opt/eosio/bin"
```
https://github.com/EOSIO/eosio-project-demux-example/blob/master/eosio_docker/scripts/continue_blockchain.sh#L9

**Comment by TaraTritt** [comment]
Thanks @jcalfee. I've opened up a PR with your suggested changes #19

**Comment by TaraTritt** [comment]
PR #19 merged. Thanks for the feedback
