### ISSUE TITLE
Ricardian contracts for actions not generated

### ISSUE THREAD

**Issue by friedger** [EOSIO/eosio-project-demux-example#30]
When I run
```
docker exec -it eosio_blog_container /opt/eosio/bin/eosiocpp -g contracts/blog/blog.abi contracts/blog/blog.cpp
```

the generated blog abi does not contain ricardian contracts for the actions.

**Comment by TaraTritt** [comment]
Yes, you will need to generate the abi with eosiocpp then modify it manually if you want to include the ricardian contracts for the actions. For example, edit the generated abi for the createpost action with the following: 
`
{
      "name": "createpost",
      "type": "createpost",
      "ricardian_contract": "---\n\nTitle: Create Post\n\nSummary: Create a blog post \"{{title}}\" by {{author}} tagged as {{tag}}\n\n---\n\n\n\nI {{author}} of the blog post \"{{title}}\" certify that I am the original author of the contents of this blog post and have attributed all external sources appropriately."
}
`
