### ISSUE TITLE
If application needs to sign a tx , then whats the approach

### ISSUE THREAD

**Issue by yashwanth2804** [EOSIO/eosio-project-demux-example#33]
Never store your private key in your frontend application, this is being stored here for demo purposes

then whats the process to follow

**Comment by TaraTritt** [comment]
You would want to use an application that would securely store your private keys and allow you to sign transactions without directly exposing your keys

**Comment by yashwanth2804** [comment]
So kind of api req/resp , where i can sign it from server end point upon getting api call  from user ,
thanks

**Comment by TaraTritt** [comment]
It depends on your use case, if you need individual users to sign transactions, you would want to use a tool that would allow them to import their own private keys and sign transactions with these keys. However, if you want your app to create and broadcast transactions, then yes having a backend service that stored the keys for your application and used them to sign transactions would also work.

**Comment by TaraTritt** [comment]
I'm not sure if I'm understanding your question correctly, but if you wanted to restrict access to who could call your contract actions, like createpost/editpost etc, you could modify the `require_auth( )` statements in the smart contract to check that only accounts with the required authorization specified can call those actions. For example, you could use `require_auth(_self)` if you wanted to ensure that the account calling the action has the authority of the account that created the contract
