### ISSUE TITLE
To deploy to the mainchain, is all we have to do is change EOSIO_CONTRACT_ACCOUNT and EOSIO_HTTP_URL to a BP node in the backend .env file?

### ISSUE THREAD

**Issue by johnworthley** [EOSIO/eosio-project-demux-example#44]

**Comment by johnworthley** [comment]
First of all, thank you for taking charge as the assistance forces. The EOS Dev telegram group must have referred me to you for a reason. 

This is not necessarily a Demux issue since this same problem would apply to the simple EOS boilerplate as well (https://github.com/EOSIO/eosio-project-boilerplate-simple). 

I am trying to comple the blog.cpp file and running `eosio-cpp -abigen blog.cpp -o blog.wasm` outside of Docker in the eosio_docker/contracts/blog folder. 

The error is as follows

Johns-MacBook-Pro-4:blog john$ eosio-cpp -abigen blog.cpp -o blog.wasm
blog.cpp:108:32: error: use of undeclared identifier 'posts'
  typedef eosio::multi_index<N(posts), post_struct,
                               ^
blog.cpp:12:30: error: no matching constructor for initialization of
      'eosio::contract'
  explicit blog(name self) : contract(self) {}
                             ^        ~~~~
/usr/local/Cellar/eosio.cdt/1.3.2/opt/eosio.cdt/bin/../include/eosiolib/contract.hpp:21:7: note:
      candidate constructor (the implicit copy constructor) not viable: no
      known conversion from 'eosio::name' to 'const eosio::contract' for
      1st argument
class contract {
      ^
/usr/local/Cellar/eosio.cdt/1.3.2/opt/eosio.cdt/bin/../include/eosiolib/contract.hpp:21:7: note:
      candidate constructor (the implicit move constructor) not viable: no
      known conversion from 'eosio::name' to 'eosio::contract' for 1st
      argument
/usr/local/Cellar/eosio.cdt/1.3.2/opt/eosio.cdt/bin/../include/eosiolib/contract.hpp:31:7: note:
      candidate constructor not viable: requires 3 arguments, but 1 was
      provided
      contract( name receiver, name code, datastream<const char*> ...
      ^
blog.cpp:24:22: error: no matching conversion for static_cast from
      'const eosio::name' to 'uint128_t' (aka 'unsigned __int128')
    uint128_t skey = static_cast<uint128_t>(author) << 64 | timestamp;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/eosio.cdt/1.3.2/opt/eosio.cdt/bin/../include/eosiolib/name.hpp:131:17: note:
      candidate function
      constexpr operator raw()const { return raw(value); }
                ^
blog.cpp:28:16: error: excess elements in scalar initializer
    post_table poststable(_self, _self); // code, scope
               ^               ~~~~~~~
blog.cpp:42:16: error: excess elements in scalar initializer
    post_table poststable(_self, _self);
               ^               ~~~~~~~
blog.cpp:45:41: error: use of undeclared identifier 'getbyskey'
    auto posts = poststable.get_index<N(getbyskey)>();
                                        ^
blog.cpp:45:53: error: expected expression
    auto posts = poststable.get_index<N(getbyskey)>();
                                                    ^
blog.cpp:46:22: error: no matching conversion for static_cast from
      'const eosio::name' to 'uint128_t' (aka 'unsigned __int128')
    uint128_t skey = static_cast<uint128_t>(author) << 64 | timestamp;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/eosio.cdt/1.3.2/opt/eosio.cdt/bin/../include/eosiolib/name.hpp:131:17: note:
      candidate function
      constexpr operator raw()const { return raw(value); }
                ^
blog.cpp:59:16: error: excess elements in scalar initializer
    post_table poststable(_self, _self);
               ^               ~~~~~~~
blog.cpp:61:41: error: use of undeclared identifier 'getbyskey'
    auto posts = poststable.get_index<N(getbyskey)>();
                                        ^
blog.cpp:61:53: error: expected expression
    auto posts = poststable.get_index<N(getbyskey)>();
                                                    ^
blog.cpp:62:22: error: no matching conversion for static_cast from
      'const eosio::name' to 'uint128_t' (aka 'unsigned __int128')
    uint128_t skey = static_cast<uint128_t>(author) << 64 | timestamp;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/eosio.cdt/1.3.2/opt/eosio.cdt/bin/../include/eosiolib/name.hpp:131:17: note:
      candidate function
      constexpr operator raw()const { return raw(value); }
                ^
blog.cpp:72:16: error: excess elements in scalar initializer
    post_table poststable(_self, _self);
               ^               ~~~~~~~
blog.cpp:74:41: error: use of undeclared identifier 'getbyskey'
    auto posts = poststable.get_index<N(getbyskey)>();
                                        ^
blog.cpp:74:53: error: expected expression
    auto posts = poststable.get_index<N(getbyskey)>();
                                                    ^
blog.cpp:75:22: error: no matching conversion for static_cast from
      'const eosio::name' to 'uint128_t' (aka 'unsigned __int128')
    uint128_t skey = static_cast<uint128_t>(author) << 64 | timestamp;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/eosio.cdt/1.3.2/opt/eosio.cdt/bin/../include/eosiolib/name.hpp:131:17: note:
      candidate function
      constexpr operator raw()const { return raw(value); }
                ^
blog.cpp:113:30: error: unknown type name 'deletepost'
EOSIO_ABI(blog, (createpost)(deletepost)(likepost)(editpost))
                             ^
blog.cpp:113:42: error: unknown type name 'likepost'
EOSIO_ABI(blog, (createpost)(deletepost)(likepost)(editpost))
                                         ^
blog.cpp:113:52: error: unknown type name 'editpost'
EOSIO_ABI(blog, (createpost)(deletepost)(likepost)(editpost))
                                                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by TaraTritt** [comment]
Hi @johnworthley glad to help. The reason you are seeing these errors is due the fact that you are using the latest CDT (contract development toolkit) to compile the blog smart contract. The master branch of this repo has not been updated to support the CDT and is still using an older version of the eosiocpp before it was migrated into the CDT. This older version of eosiocpp is what you see being referred to in the compile and deploy scripts for the smart contract. We are in the process of updating these scripts and the smart contract to use latest CDT tools and syntax. If you want to check out it out the branch is [cdt-update](https://github.com/EOSIO/eosio-project-demux-example/tree/cdt-update) the simple boilerplate also has a [PR](https://github.com/EOSIO/eosio-project-boilerplate-simple/pull/23) up which shows all the changes necessary to support the latest CDT tools

**Comment by johnworthley** [comment]
To deploy to mainnet-

1. Delete `./start_eosio_docker.sh --nolog` from quick_start.sh
2. Replace `REACT_APP_EOSIO_HTTP_URL`(.env in the frontend folder) and EOSIO_HTTP_URL(.env in the backend folder)with a block producer of your choice 
(i.e. 
REACT_APP_EOSIO_HTTP_URL=https://api.eosnewyork.io:443;
EOSIO_HTTP_URL=https://api.eosnewyork.io:443
)
3. Manually deploy the smart contract from the eosio_docker folder

I believe EOS's first deployable and working boilerplate application for use by all future hackathon teams and projects has arrived :)

Great work Tara! Keep on flying!!
